src/web/GISA.WebApp.MVC/Controllers/AuthController.cs
using System;
using System.Collections.Generic;
using System.IdentityModel.Tokens.Jwt;
using System.Security.Claims;
using System.Threading.Tasks;
using GISA.WebApp.MVC.Models;
using GISA.WebApp.MVC.Services;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace GISA.WebApp.MVC.Controllers
{
    [Authorize]
    public class AuthController : MainController
    {
        private readonly IAutenticacaoService _autenticacaoService;

        public AuthController(IAutenticacaoService autenticacaoService)
            => _autenticacaoService = autenticacaoService;

        [HttpGet]
        [Route("auth/novo-cliente")]
        public IActionResult RegistroCliente()
            => View();

        [HttpPost]
        [Route("auth/novo-cliente")]
        public async Task<IActionResult> RegistroCliente(UsuarioRegistro usuarioRegistro)
        {
            if (!ModelState.IsValid)
            {
                return View(usuarioRegistro);
            }

            var resposta = await _autenticacaoService.RegistroCliente(usuarioRegistro);
            return ResponsePossuiErros(resposta.ResponseResult) ?
                View(usuarioRegistro) : (IActionResult)RedirectToAction("Index", "Pessoa");
        }

        [HttpGet]
        [Route("auth/novo-admin")]
        public IActionResult Registro()
            => View();

        [HttpPost]
        [Route("auth/novo-admin")]
        public async Task<IActionResult> Registro(UsuarioRegistro usuarioRegistro)
        {
            if (!ModelState.IsValid)
            {
                return View(usuarioRegistro);
            }

            var resposta = await _autenticacaoService.Registro(usuarioRegistro);
            if (ResponsePossuiErros(resposta.ResponseResult))
            {
                return View(usuarioRegistro);
            }

            await RealizarLogin(resposta);
            return RedirectToAction("Index", "Home");
        }

        [AllowAnonymous]
        [HttpGet]
        [Route("login")]
        public IActionResult Login(string returnUrl = null)
        {
            ViewData["ReturnUrl"] = returnUrl;
            return View();
        }

        [AllowAnonymous]
        [HttpPost]
        [Route("login")]
        public async Task<IActionResult> Login(UsuarioLogin usuarioLogin, string returnUrl = null)
        {
            ViewData["ReturnUrl"] = returnUrl;
            if (!ModelState.IsValid)
            {
                return View(usuarioLogin);
            }

            var resposta = await _autenticacaoService.Login(usuarioLogin);
            if (ResponsePossuiErros(resposta.ResponseResult))
            {
                return View(usuarioLogin);
            }

            await RealizarLogin(resposta);
            return string.IsNullOrWhiteSpace(returnUrl) ?
                RedirectToAction("Apresentacao", "Home") : (IActionResult)LocalRedirect(returnUrl);
        }

        [HttpGet]
        [Route("auth/logout")]
        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction("Index", "Home");
        }

        private async Task RealizarLogin(UsuarioRespostaLogin resposta)
        {
            var token = ObterTokenFormatado(resposta.AccessToken);

            var claims = new List<Claim>
            {
                new Claim("JWT", resposta.AccessToken)
            };
            claims.AddRange(token.Claims);

            var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);

            var authProperties = new AuthenticationProperties
            {
                ExpiresUtc = DateTimeOffset.UtcNow.AddMinutes(60),
                IsPersistent = true
            };

            await HttpContext.SignInAsync(
                CookieAuthenticationDefaults.AuthenticationScheme,
                new ClaimsPrincipal(claimsIdentity),
                authProperties);
        }

        private static JwtSecurityToken ObterTokenFormatado(string jwtToken)
            => new JwtSecurityTokenHandler().ReadToken(jwtToken) as JwtSecurityToken;
    }
}

src/web/GISA.WebApp.MVC/Controllers/DashboardController.cs
using System.Threading.Tasks;
using GISA.WebApp.MVC.Models;
using GISA.WebApp.MVC.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace GISA.WebApp.MVC.Controllers
{
    [Authorize]
    public class DashboardController : MainController
    {
        private readonly IConvenioService _convenioService;
        private readonly IPessoaService _pessoaService;
        private readonly IPlanoService _planoService;

        public DashboardController(IConvenioService convenioService, IPessoaService pessoaService, IPlanoService planoService)
        {
            _convenioService = convenioService;
            _pessoaService = pessoaService;
            _planoService = planoService;
        }

        [HttpGet]
        [Route("dashboard")]
        public async Task<IActionResult> Index()
        {
            var obterTotalConvenio = await _convenioService.ObterTotalConvenio();

            var obterTotalUsuario = await _pessoaService.ObterTotalUsuario();
            var obterTotalUsuarioAtivo = await _pessoaService.ObterTotalUsuarioAtivo();
            var obterTotalUsuarioInativo = await _pessoaService.ObterTotalUsuarioInativo();

            var obterTotalPlano = await _planoService.ObterTotalPlano();
            var obterTotalPlanoAtivo = await _planoService.ObterTotalPlanoAtivo();
            var obterTotalPlanoInativo = await _planoService.ObterTotalPlanoInativo();

            return View(new DashboardViewModels
            {
                TotalUsuario = obterTotalUsuario,
                TotalAtivo = obterTotalUsuarioAtivo,
                TotalInativo = obterTotalUsuarioInativo,
                TotalConvenio = obterTotalConvenio,
                TotalPlano = obterTotalPlano,
                PlanoVendido = obterTotalPlanoAtivo,
                PlanoCancelado = obterTotalPlanoInativo,
            });
        }
    }
}

src/web/GISA.WebApp.MVC/Views/Shared/_Layout.cshtml
@model GISA.WebApp.MVC.Models.UsuarioLogin

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

src/web/GISA.WebApp.MVC/Views/Shared/_LayoutPrivate.cshtml
@using GISA.WebApp.MVC.Extensions
@using GISA.WebApi.Core.Usuario
@inject IAspNetUser AppUser

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>@ViewData["Title"] | Boa Saúde</title>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href='https://cdn.jsdelivr.net/npm/boxicons@latest/css/boxicons.min.css' rel='stylesheet'>
    <link href="//cdn.datatables.net/1.11.3/css/jquery.dataTables.min.css" rel="stylesheet" />
    <link href="~/css/dist/bootstrap-datepicker.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body id="body-pd" class='snippet-body'>
    <header class="header" id="header">
        <partial name="_LoginPartial" />
    </header>

    <div class="l-navbar" id="nav-bar">
        <nav class="nav">

            <div>
                <a asp-action="Apresentacao" asp-controller="Home" class="nav_logo"><i class='bx bx-layer nav_logo-icon'></i><span class="nav_logo-name">Boa Saúde</span></a>
                <div class="nav_list">
                    @{
                        if (AppUser.RoleAdmin() == true)
                        {
                            <a asp-action="Index" asp-controller="Dashboard" class="nav_link"><i class='bx bx-grid-alt nav_icon'></i><span class="nav_name">Dashboard</span></a>
                            <a asp-action="Index" asp-controller="Agenda" class="nav_link"><i class='bx bx-notepad nav_icon'></i><span class="nav_name">Agenda</span></a>
                            <a asp-action="Index" asp-controller="Pessoa" class="nav_link"><i class='bx bx-user nav_icon'></i><span class="nav_name">Pessoa</span></a>
                            <a asp-action="Index" asp-controller="Convenio" class="nav_link"><i class='bx bx-briefcase nav_icon'></i><span class="nav_name">Convenio</span></a>
                            <a asp-action="Index" asp-controller="Plano" class="nav_link"><i class='bx bx-food-menu'></i><span class="nav_name">Plano</span></a>
                        }
                        else
                        {
                            <a asp-action="MinhaAgenda" asp-controller="Agenda" class="nav_link"> <i class='bx bx-book-heart'></i> <span class="nav_name">Minha Agenda</span> </a>
                        }
                    }
                </div>
            </div>
            <a asp-action="Index" asp-controller="Administrador" class="nav_link"> <i class='bx bx-cog nav_icon'></i> <span class="nav_name">Configurações</span> </a>
        </nav>
    </div>

    <div class="height-100">
        @RenderBody()
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/jquery-mask/jquery.mask.min.js"></script>
    <script src="~/js/dist/bootstrap-datepicker.min.js"></script>
    <script src="~/js/dist/bootstrap-datepicker.pt-BR.min.js"></script>

    <script src="//cdn.datatables.net/1.11.3/js/jquery.dataTables.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <script type='text/javascript'>
        app.eventos.init();

        // Routers
        function EditarAgenda(id) {
            window.location.href = `@Url.Action("Editar", "Agenda")/${id}`;
        }

        function EditarPlano(id) {
            window.location.href = `@Url.Action("Editar", "Plano")/${id}`;
        }

        function EditarConvenio(id) {
            window.location.href = `@Url.Action("Editar", "Convenio")/${id}`;
        }

        function EditarPessoa(id) {
            window.location.href = `@Url.Action("Editar", "Pessoa")/${id}`;
        }

        function EditarUsuario() {
            window.location.href = `@Url.Action("RegistroCliente", "Auth")`;
        }

        // Menu
        document.addEventListener("DOMContentLoaded", function (event) {

            const showNavbar = (toggleId, navId, bodyId, headerId, headerManagement) => {
                const toggle = document.getElementById(toggleId),
                    nav = document.getElementById(navId),
                    bodypd = document.getElementById(bodyId),
                    headerpd = document.getElementById(headerId),
                    headerManagementmg = document.getElementById(headerManagement)

                // Validate that all variables exist
                if (toggle && nav && bodypd && headerpd) {
                    toggle.addEventListener('click', () => {
                        // show navbar
                        nav.classList.toggle('show-nav')
                        // change icon
                        toggle.classList.toggle('bx-x')
                        // add padding to body
                        bodypd.classList.toggle('body-pd')
                        // add padding to header
                        headerpd.classList.toggle('body-pd')
                        // add margin to header title management page
                        headerManagementmg.classList.toggle("ml-155")
                    })
                }
            }

            showNavbar('header-toggle', 'nav-bar', 'body-pd', 'header', 'header-management')

            /*===== LINK ACTIVE =====*/
            const linkColor = document.querySelectorAll('.nav_link')

            function colorLink() {
                if (linkColor) {
                    linkColor.forEach(l => l.classList.remove('active'))
                    this.classList.add('active')
                }
            }
            linkColor.forEach(l => l.addEventListener('click', colorLink))

            // Your code to run since DOM is loaded and ready
        });
    </script>

    @RenderSection("Scripts", required: false)
</body>
</html>

src/web/GISA.WebApp.MVC/Views/Shared/_MenuPartial.cshtml
<div class="flex-shrink-0 p-3 bg-white mb-0" style="width: 280px;">
    <a href="/" class="d-flex align-items-center pb-3 mb-3 link-dark text-decoration-none border-bottom">
        <svg class="bi me-2" width="30" height="24"><use xlink:href="#bootstrap"></use></svg>
        <span class="fs-5 fw-semibold">Collapsible</span>
    </a>
    <ul class="list-unstyled ps-0">
        <li class="mb-1">
            <button class="btn btn-toggle align-items-center rounded collapsed" data-bs-toggle="collapse" data-bs-target="#home-collapse" aria-expanded="false">
                Home
            </button>
            <div class="collapse" id="home-collapse" style="">
                <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
                    <li><a href="#" class="link-dark rounded">Overview</a></li>
                    <li><a href="#" class="link-dark rounded">Updates</a></li>
                    <li><a href="#" class="link-dark rounded">Reports</a></li>
                </ul>
            </div>
        </li>
        <li class="mb-1">
            <button class="btn btn-toggle align-items-center rounded collapsed" data-bs-toggle="collapse" data-bs-target="#dashboard-collapse" aria-expanded="false">
                Dashboard
            </button>
            <div class="collapse" id="dashboard-collapse" style="">
                <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
                    <li><a href="#" class="link-dark rounded">Overview</a></li>
                    <li><a href="#" class="link-dark rounded">Weekly</a></li>
                    <li><a href="#" class="link-dark rounded">Monthly</a></li>
                    <li><a href="#" class="link-dark rounded">Annually</a></li>
                </ul>
            </div>
        </li>
        <li class="mb-1">
            <button class="btn btn-toggle align-items-center rounded collapsed" data-bs-toggle="collapse" data-bs-target="#orders-collapse" aria-expanded="false">
                Orders
            </button>
            <div class="collapse" id="orders-collapse">
                <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
                    <li><a href="#" class="link-dark rounded">New</a></li>
                    <li><a href="#" class="link-dark rounded">Processed</a></li>
                    <li><a href="#" class="link-dark rounded">Shipped</a></li>
                    <li><a href="#" class="link-dark rounded">Returned</a></li>
                </ul>
            </div>
        </li>
        <li class="border-top my-3"></li>
        <li class="mb-1">
            <button class="btn btn-toggle align-items-center rounded collapsed" data-bs-toggle="collapse" data-bs-target="#account-collapse" aria-expanded="false">
                Account
            </button>
            <div class="collapse" id="account-collapse">
                <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
                    <li><a href="#" class="link-dark rounded">New...</a></li>
                    <li><a href="#" class="link-dark rounded">Profile</a></li>
                    <li><a href="#" class="link-dark rounded">Settings</a></li>
                    <li><a href="#" class="link-dark rounded">Sign out</a></li>
                </ul>
            </div>
        </li>
    </ul>
</div>